version: "3"

networks:
  ethernet:
    external: true

services:
  gl-auth-php:
    container_name: gl-auth-php
    image: gl-auth/php
    build: .docker/php
    env_file:
      - .docker/php/.env
    volumes:
      - ./:/var/www/auth
    links:
      - gl-auth-mariadb
    depends_on:
      - gl-auth-mariadb
    networks:
      - ethernet

  gl-auth-mariadb:
    container_name: gl-auth-mariadb
    image: gl-auth/mariadb
    build:
      context: .
      dockerfile: .docker/mariadb/Dockerfile
    volumes:
      - ./.docker-runtime/:/bitnami
    ports:
      - "3307:3306"
    env_file:
      - .docker/mariadb/.env
    networks:
      - ethernet

  gl-auth-nginx:
    container_name: gl-auth-nginx
    image: gl-auth/nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/auth
    links:
      - gl-auth-php
    ports:
      - "81:80"
      - "444:443"
    networks:
      - ethernet